version: "3.4"

services:
  redis:
    image: redis:7
    restart: always
    networks:
      - springtechincalstack
    container_name: redis
    volumes:
      - booking-redis:/data
    ports:
      - '6379:6379'


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq
    networks:
      - springtechincalstack_nw

  springtechincalstack:
    container_name: springtechincalstack_nw
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
    ports:
      - "8181:8080"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - springtechincalstack_nw

volumes:

  booking-es:
    driver: local


networks:
  springtechincalstack_nw:
    driver: bridge